apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv-volume
  namespace: default
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/backend"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
