apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: peachide
  namespace: default
spec:
  secretName: peachide
  commonName: peach.benx.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 72h
  dnsNames:
    - peach.benx.dev
