name: Deploy to PeachIDE server

on:
  push:
    branches: ["main"]
    paths:
      - 'peachide/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'peachide/**'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build image and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: chanbengz
        password: ${{ secrets.HUB_GITHUB_TOKEN }}

    - name: Build and push Docker image
      working-directory: peachide
      run: |
        docker build . --file Dockerfile --tag ghcr.io/chanbengz/peachide:latest
        docker push ghcr.io/chanbengz/peachide:latest

    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: kubectl rollout restart deployment/peachide
