name: Build Next.js App Container

on:
  push:
    branches: ["main"]
    paths:
      - 'peachide'
  pull_request:
    branches: ["main"]
    paths:
      - 'peachide'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: chanbengz
        password: ${{ secrets.HUB_GITHUB_TOKEN }}

    - name: Build and push Docker image
      working-directory: peachide
      run: |
        docker build . --file Dockerfile --tag ghcr.io/chanbengz/peachide:$(date +%s)
        docker push ghcr.io/chanbengz/peachide:$(date +%s)